// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gosii

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2189435aDecodeGithubComEitolGosii(in *jlexer.Lexer, out *CommercialActivity) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2189435aEncodeGithubComEitolGosii(out *jwriter.Writer, in CommercialActivity) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommercialActivity) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2189435aEncodeGithubComEitolGosii(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommercialActivity) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2189435aEncodeGithubComEitolGosii(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommercialActivity) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2189435aDecodeGithubComEitolGosii(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommercialActivity) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2189435aDecodeGithubComEitolGosii(l, v)
}
func easyjson2189435aDecodeGithubComEitolGosii1(in *jlexer.Lexer, out *Citizen) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "rut":
			out.Rut = string(in.String())
		case "run":
			out.Run = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "activities":
			if in.IsNull() {
				in.Skip()
				out.Activities = nil
			} else {
				in.Delim('[')
				if out.Activities == nil {
					if !in.IsDelim(']') {
						out.Activities = make([]CommercialActivity, 0, 2)
					} else {
						out.Activities = []CommercialActivity{}
					}
				} else {
					out.Activities = (out.Activities)[:0]
				}
				for !in.IsDelim(']') {
					var v1 CommercialActivity
					(v1).UnmarshalEasyJSON(in)
					out.Activities = append(out.Activities, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2189435aEncodeGithubComEitolGosii1(out *jwriter.Writer, in Citizen) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rut\":"
		out.RawString(prefix[1:])
		out.String(string(in.Rut))
	}
	{
		const prefix string = ",\"run\":"
		out.RawString(prefix)
		out.String(string(in.Run))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"activities\":"
		out.RawString(prefix)
		if in.Activities == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Activities {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Citizen) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2189435aEncodeGithubComEitolGosii1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Citizen) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2189435aEncodeGithubComEitolGosii1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Citizen) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2189435aDecodeGithubComEitolGosii1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Citizen) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2189435aDecodeGithubComEitolGosii1(l, v)
}
func easyjson2189435aDecodeGithubComEitolGosii2(in *jlexer.Lexer, out *CaptchaResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "txtCaptcha":
			out.TxtCaptcha = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2189435aEncodeGithubComEitolGosii2(out *jwriter.Writer, in CaptchaResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txtCaptcha\":"
		out.RawString(prefix[1:])
		out.String(string(in.TxtCaptcha))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CaptchaResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2189435aEncodeGithubComEitolGosii2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CaptchaResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2189435aEncodeGithubComEitolGosii2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CaptchaResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2189435aDecodeGithubComEitolGosii2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CaptchaResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2189435aDecodeGithubComEitolGosii2(l, v)
}
